### ISSUE TITLE
Android release compilations fail

### ISSUE THREAD

**Issue by codebymikey** [PrestoDoctor/react-native-browser#8]
Android release compilation fails with this error:

```
com.facebook.react.common.JavascriptException: Requiring unknown module "react-native-browser"., stack:
                                                   n@2:700
                                                   o@2:404
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@673:255
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@383:403
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@12:40
                                                   o@2:517
                                                   e@2:256
                                                   i@2:188
                                                   global code@824:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:234)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)
```

This is because the package.json is set to `"main": "index.ios.js",` rather than `"main": "index.android.js",` on android

**Comment by codebymikey** [comment]
Solution:

change package.json `"main": "index.ios.js",` line to `"main": "main.js",`

and in the `main.js` file, use:

```js
export default require('./index');
```

**Comment by mfkp** [comment]
Thanks @codebymikey - if you send a pull request with that change I can get it merged.

**Comment by onosol** [comment]
Has this fix been merged into the latest release?

**Comment by mcnamee** [comment]
@mfkp Are you able to test and merge the pull request?
